metadata:
  author: FOSSASIA
  projectname: "Kumar Server"
  version: development
build:
  theme: sphinx_fossasia_theme   
  source: docs
  logo: images/kumar-logo-original.svg
  subproject:
    - url: https://github.com/fossasia/kumar_android
      source: docs
    - url: https://github.com/fossasia/chat.kumar.ai
      source: docs
    - url: https://github.com/fossasia/kumar_tweetbot
      source: docs
    - url: https://github.com/fossasia/kumar_fbbot
      source: docs
    - url: https://github.com/fossasia/kumar_slackbot
      source: docs
    - url: https://github.com/fossasia/kumar_desktop
      source: .
    - url: https://github.com/fossasia/kumar_iOS
      source: docs
    - url: https://github.com/fossasia/kumar_telegrambot
      source: docs
publish:
  ghpages:
    docurl: dev.kumar.ai
extras:
  swagger:
    url: http://api.kumar.ai/docs/swagger.json
    ui: swagger  
  javadoc:
    path: 'src/'
