#
# Deployment of the KUMAR Server
#
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kumar-server
  namespace: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kumar-server
    spec:
      nodeSelector:
        server: primary
      containers:
      - name: kumar-server
        image: fossasia/kumar_server:latest-development
        volumeMounts:
          - mountPath: /kumar_server/data
            name: server-data
        livenessProbe:
          httpGet:
            path: /kumar/status.json
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 3
        ports:
        - containerPort: 80
          protocol: TCP
      volumes:
      - name: server-data
        persistentVolumeClaim:
          claimName: server-data-claim